### DISCUSSION TITLE
I need to submit the of repositories A to the directory of repositories B

### DISCUSSION THREAD

**Discussion by adaLucky** [s0/git-publish-subdir-action#64] [Q&A / Help & Support] [answered]
![Ada2021-09-09_10-54-08](https://user-images.githubusercontent.com/49558910/132616229-11f611bc-1eac-4eef-abab-6fd604096408.png)

I need to submit the source/census/data of repositories A to the census/data directory of repositories B. how should I configure it.  I hope to get your help

 - name: 5、push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:adaLucky/adaLucky.github.io.git
          BRANCH: main
          FOLDER: source/census/data
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

**Comment by s0** [comment, marked as answer]
@adaLucky sorry for the delay in this.

It's a little bit awkward to do this right now (and I've created an issue here to hopefully simplify it: #70), but you can do this using something like the following:

Create a file `.clear-target-files` that has:

```
census/data/**/*
```

And add a workflow that looks like:

```yml
jobs:
  deploy:
    steps:
    #...
    - name: replicate directory structure
      run: |
        mkdir -p remote/census/data
        cp -rT source/census/data/ remote/census/data/
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        FOLDER: remote
        CLEAR_GLOBS_FILE: ".clear-target-files"
        #...
```
