### DISCUSSION TITLE
I want to place it in the designated folder of target warehouse, not the root directory. How do I do that？

### DISCUSSION THREAD

**Discussion by Chasen-Zhang** [s0/git-publish-subdir-action#65] [Q&A / Help & Support] [answered]
I want to place it in the designated folder of target warehouse, not the root directory. How do I do that？

**Comment by s0** [comment, marked as answer]
Hi @Chasen-Zhang 

It's a little bit awkward to do this right now (and I've created an issue here to hopefully simplify it: https://github.com/s0/git-publish-subdir-action/issues/70), but you can do this now using something like the following:

You would currently need to place the target files in a path in the `FOLDER` directory that matches the desired target path in the remote directory.

So if for example you wanted the files in `foo/bar` to be copied to the path `cat/dog/bar` then you would do something like this:

Create a file `.clear-target-files` that has:

```
cat/dog/bar/**/*
```

And add a workflow that looks like:

```yml
jobs:
  deploy:
    steps:
    #...
    - name: replicate directory structure
      run: |
        mkdir -p remote/cat/dog/bar
        cp -rT foo/bar/ remote/cat/dog/bar/
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        FOLDER: remote
        CLEAR_GLOBS_FILE: ".clear-target-files"
        #...
```
