### ISSUE TITLE
Folder names with spaces are not supported

### ISSUE THREAD

**Issue by AndrewMJordan** [s0/git-publish-subdir-action#32]
If the value of `FOLDER` contains spaces, this causes the step to fail.

```
- uses: s0/git-publish-subdir-action@develop
  env:
    REPO: self
    BRANCH: upm
    FOLDER: "Directory With Spaces"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

 The workflow log reveals that the arguments to a `cp` are not wrapped with quotations.
