### ISSUE TITLE
some directory not publish success,others works will

### ISSUE THREAD

**Issue by ileeoyo** [s0/git-publish-subdir-action#47]
partial workflow file
```
- name: PreDeploy
              run: |
                  sudo ls -al tmp
                  sudo ls -al tmp/files/profiles
- name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: url
            BRANCH: master
            FOLDER: tmp
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
```

out log
```
total 68
drwxr-xr-x 5 runner docker  4096 May 21 09:35 .
drwxr-xr-x 6 runner docker  4096 May 21 09:35 ..
-rw-r--r-- 1 root   root   35149 May 21 09:35 LICENSE
-rw-r--r-- 1 root   root     225 May 21 09:35 README.md
-rw-r--r-- 1 root   root     389 May 21 09:35 bootstrap.sh
drwxr-xr-x 4 root   root    4096 May 21 09:35 files
-rw-r--r-- 1 root   root    1046 May 21 09:35 now.json
drwxr-xr-x 5 root   root    4096 May 21 09:35 sub-web
drwxr-xr-x 8 root   root    4096 May 21 09:35 subconverter
total 20
drwxr-xr-x 2 root root 4096 May 21 09:35 .
drwxr-xr-x 4 root root 4096 May 21 09:35 ..
-rw-r--r-- 1 root root  284 May 21 09:35 china.ini
-rw-r--r-- 1 root root  427 May 21 09:35 free.ini
-rw-r--r-- 1 root root  286 May 21 09:35 free2.ini
```

all published success except `files`
