### ISSUE TITLE
SSH_PRIVATE_KEY does not work on Windows workers

### ISSUE THREAD

**Issue by caibinwav123456** [s0/git-publish-subdir-action#48]
Which form should the env variable SSH_PRIVATE_KEY actually take?
I used the following statement literally:

SSH_PRIVATE_KEY: ${{secrets.PRIVK}} #PRIVK is the Deploy Key corresponding private key name added to the repo settings->secrets

And it simply got the error:

Error: SSH_PRIVATE_KEY must be specified when REPO uses ssh

**Comment by caibinwav123456** [comment]
See attachment:

![2021-05-25](https://user-images.githubusercontent.com/46627288/119475806-0b6ba680-bd80-11eb-9826-ef2249100935.png)

**Comment by caibinwav123456** [comment]
s0 is an SOB!!!
For you don't answer my question.

**Comment by s0** [comment]
Apologies, GitHub notifications can sometimes go unseen.

The most likely cause in this case is that the secret is empty? Could you try Updating it with the key contents again?

**Comment by s0** [comment]
One other things that occurs to me actually is that secrets are not always accessible (e.g. for actions triggered by dependabot PRs, PRs opened from forked repos, etc...). Which action type is this being used in?

**Comment by caibinwav123456** [comment]
Thanks for reply.
Yet now it's not the problem that bothers me. I've not got the solution for long so I began trying to explore it myself.

The situation is that I am building my project in repository A on windows-latest. And it generates an output in the local path on github hosted server: <PATH_BUILD_LOCAL>/output.exe  (it's typically an installation package of the APP that has been built)

And I want to publish or say deploy it on repository B:<PATH_DEPLOY>/output.exe (in certain branch such as main ...)

I've discovered that when you specify the env var in the action yml file in A:
SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
You are actually accessing the secrets named DEPLOY_PRIVATE_KEY in repo A.

So I generate an rsa key pair locally with ssh-keygen and upload the content of the private key file id_rsa to the secrets of A and name it DEPLOY_PRIVATE_KEY, while uploading the content of the public key file id_rsa.pub to be the deploy key of repository B. And I used the statement in the action yml file in A:

    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:xxxxxx/xxx.git
        BRANCH: main
        FOLDER: <PATH_BUILD_LOCAL>
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}

After all that was done. I went on to run the action in repo A, but it still got errors:

Run s0/git-publish-subdir-action@develop
  env:
    REPO: git@github.com:xxxxxx/xxx.git
    BRANCH: main
    FOLDER: <PATH_BUILD_LOCAL>
    SSH_PRIVATE_KEY: ***
  
##[info] Not running in git directory, unable to get information about source commit
Setting up ssh-agent on C:\Users\RUNNER~1\AppData\Local\Temp\git-publish-subdir-action-8k6sut\ssh_agent.sock
data SSH_AUTH_SOCK=C:UsersRUNNER~1AppDataLocalTempgit-publish-subdir-action-8k6sutssh_agent.sock; export SSH_AUTH_SOCK;
SSH_AGENT_PID=1543; export SSH_AGENT_PID;
echo Agent pid 1543;

Adding private key to ssh-agent at C:\Users\RUNNER~1\AppData\Local\Temp\git-publish-subdir-action-8k6sut\ssh_agent.sock
Error connecting to agent: No such file or directory

Error: Error connecting to agent: No such file or directory

    at ChildProcess.<anonymous> (D:\a\_actions\s0\git-publish-subdir-action\develop\action\dist\index.js:12457:20)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Moreover, I thought I need to specify two paths: <PATH_BUILD_LOCAL> & <PATH_DEPLOY>, as described above, but I only found the FOLDER environment variable in which I can specify one path.

The yml file is attached below (it's for test only, as it omits all steps other than publish).
[msbuild_test.zip](https://github.com/s0/git-publish-subdir-action/files/6572643/msbuild_test.zip)

**Comment by caibinwav123456** [comment]
I've constructed two public repositories:

https://github.com/caibinwav123456/Test-Pub.git

publishing to:

https://github.com/caibinwav123456/Pub.git

you can run Test Pub Action on Test-Pub.git and test it yourself.

It got the same issue as I mentioned before.

**Comment by s0** [comment]
Ahh! That will be because you're using windows workers, this repo hasn't been tested on windows workers, so that needs to change.

The crux of the issue is that `ssh-agent` uses sockets, but sockets in Windows work differently to Unix (as they are named and don't use paths). We're making assumptions about the socket name that break under Windows.

**Comment by caibinwav123456** [comment]
So is there a plan in future for this action to be transplanted onto Windows? Or can you give some advice for any substitutions that I can use on Windows?

**Comment by s0** [comment]
@caibinwav123456 I had a go at getting this working on windows but it seemed to be quite involved and I wasn't able to come up with a fix yet.

In the meantime, you could make use of action artifacts to pass the build from the windows worker to a linux worker to deploy, something like this seems to work well:

```yml
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: files-to-publish
        path: build
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: files-to-publish
        path: build
    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:caibinwav123456/Pub.git
        BRANCH: main
        FOLDER: build
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
    ```
