### ISSUE TITLE
CRIT: autoselect a main branch

### ISSUE THREAD

**Issue by eXponenta** [s0/git-publish-subdir-action#90]
Critical bug.
If something will with target branch, automatically will selected a 'main'

This is **forbidden** beckhaviour, task SHOULD CRASH in this case.

![image](https://user-images.githubusercontent.com/12572222/204879387-2e8bd2e9-c89a-4956-8c97-9db58623997f.png)

**Comment by s0** [comment]
Hi @eXponenta,

Could you share the config for this step from your workflow yaml file that runs this?

Cheers,
Sam.

**Comment by eXponenta** [comment]
@s0 

This is my miss that revealed this critical

config:

```
name: Update VR Template after build
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
env:
  FROM_BRANCH: main
  FROM_FOLDER: dist.s3
  TARGET_REPO:  <secret>//
  TARGET_BRACH: master-test
  TARGE_FOLDER: webxr.new
jobs:
  update:
    name: Deploy in template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.FROM_BRANCH }}
    - name: Set Git config
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: ${{ env.TARGET_REPO }}
        BRANCH: ${{ env.TARGET_BRACH }} # <<-- was a FROM_BRANCH, i did a miss 
        FOLDER: ${{ env.FROM_FOLDER }}
        TARGET_DIR: ${{ env.TARGE_FOLDER }}
        SKIP_EMPTY_COMMITS: true
        MESSAGE: Auto generated commit
        SSH_PRIVATE_KEY: ${{ secrets.VR_PLAYER_DEPLOY }}
        KNOWN_HOSTS_FILE: .github/known_hosts # Path relative to the root of the repository
```

I think this is undefined behaviour, when we push to specific branch that not exist and should stop task
