### ISSUE TITLE
Output deployment status

### ISSUE THREAD

**Issue by wopian** [s0/git-publish-subdir-action#92]
I'm using this action to deploy built files to a branch, which works great.

I've setup the action to use `SKIP_EMPTY_COMMITS`, however I'm unable to use this to its full effect of reducing unwanted noise.

As the action passes without outputting anything, I cannot skip sending a "restart to pull changes" command to production services.

It would be incredibly useful to have an output that describes the state when the action passess successfully, such as:

```yml
state: 'pushed' | 'skipped'
```

E.g this example that would only run the `some/other-action` action if this action outputted a `pushed` state:

```yml
jobs:
  deploy:
  ...
  - uses: s0/git-publish-subdir-action@develop
    id: publish # sets custom id for step to reuse its outputs
  - uses: some/other-action@develop
    if: steps.publish.outputs.state == 'pushed' # only gets run if there's "new" changes
```

Documentation on using Action outputs: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=bash#about-workflow-commands
