### ISSUE TITLE
dist folder not found on deploy

### ISSUE THREAD

**Issue by Tpleme** [s0/git-publish-subdir-action#97]
Hello, I've just recently started to work with github actions, and i am trying to automate the build and deploy to a new branch of a vite project. But i am getting an error about not finding the dist folder after build step is performed.

**Detail to note: The project to build is inside a folder named "client".**

This is my workflow file:

```
name: Generate a build and deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
        run:
          working-directory: ./client
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build
    
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}"

```

Only the deploy step fail with this error:

![image](https://github.com/s0/git-publish-subdir-action/assets/72796924/ee260534-9bad-47c3-b1ea-efe0d5090dd2)

What am i doing wrong in the workflow configuration?
