### ISSUE TITLE
Custom commit message parameters are blank

### ISSUE THREAD

**Issue by kg583** [s0/git-publish-subdir-action#98]
I am using the following workflow file to build files that live on another branch:
```yaml
- name: Save to built branch
  uses: s0/git-publish-subdir-action@develop
  env:
    REPO: self
    BRANCH: built
    FOLDER: built
    SKIP_EMPTY_COMMITS: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    MESSAGE: "Build {sha}: {msg}"
```

However, the generated commit message does not substitute the SHA or source commit message:
>
> [1f3d40f](https://github.com/TI-Toolkit/tokens/commit/1f3d40f52e09d11ae248a4d9007c468ac96cc8d4) Build : - kg583
